# Generated by Django 4.1.6 on 2023-02-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstaTonneApis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
