# Generated by Django 4.1.6 on 2023-02-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstaTonneApis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='userID',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
    ]
