# Generated by Django 4.1.6 on 2023-03-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstaTonneApis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedserver',
            name='api',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
