# Generated by Django 4.1.6 on 2023-02-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstaTonneApis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='catagories',
            new_name='categories',
        ),
        migrations.AddField(
            model_name='author',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='userID',
            field=models.TextField(default='0'),
        ),
    ]
