# Generated by Django 4.1.6 on 2023-02-11 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InstaTonneApis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='display_name',
            new_name='displayName',
        ),
    ]
