# Generated by Django 4.1.6 on 2023-03-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstaTonneApis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.TextField()),
                ('creds', models.TextField()),
            ],
        ),
    ]
