# Generated by Django 4.1.6 on 2023-02-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstaTonneApis', '0002_author_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
