# Generated by Django 4.1.6 on 2023-02-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstaTonneApis', '0002_rename_display_name_author_displayname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author1Id', models.TextField()),
                ('author2Id', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='followings',
        ),
    ]
