# Generated by Django 4.1.6 on 2023-03-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstaTonneApis', '0002_connectedserver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectedserver',
            old_name='creds',
            new_name='accepted_creds',
        ),
        migrations.AddField(
            model_name='connectedserver',
            name='our_creds',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
