# Generated by Django 4.1.6 on 2023-02-12 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InstaTonneApis', '0003_follows_remove_author_followings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='profile_image',
            new_name='profileImage',
        ),
    ]
