# Generated by Django 4.1.6 on 2023-02-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstaTonneApis', '0009_inbox_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='id',
        ),
        migrations.AlterField(
            model_name='author',
            name='userID',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
